### ISSUE TITLE
Does not run on OS X

### ISSUE THREAD

**Issue by BleuLlama** [robzed/LuaZ80#2]
On an OS X system with nothing special installed (just lua 5.1.4), and trying to run any of the examples mentioned on the main page, I get the following error:

```
  # lua lua_z80_test.lua
  Lua 5.1
  lua: ./lua_z80.lua:1278: variable 'bit32' is not declared
  stack traceback:
  	[C]: in function 'error'
  	./third_party/strict.lua:37: in function <./third_party/strict.lua:35>
  	./lua_z80.lua:1278: in main chunk
  	[C]: in function 'require'
  	lua_z80_test.lua:35: in main chunk
  	[C]: ?`
```
(edited for formatting)

**Comment by robzed** [comment]
Hi @BleuLlama ,

You require Lua 5.2 to run LuaZ80 - try that Lua version. 

The error you've printed specifically is about bit32 - the bitwise operator library introduced in Lua 5.2. This relatively easy fix for Lua 5.1. 

However, the goto statement is required to compile/translate branches (jr, jp). The goto statement appeared first in Lua 5.2. This is going to be very difficult to fix without a complete re-write. I've added some notes to technical.txt.
 
Lua 5.3 and LuaJIT both support goto - but I haven't tested it against either of these yet. And I would strongly suspect there would be  #other changes to get them successfully running.

I've added a few more notes in the documentation so that it's clearer this is required (see this commit f9bcde109a31edafe4763be1268d6350d5989ceb). Let me know if you see any other problems.

**Comment by BleuLlama** [comment]
Aha! That makes total sense.  I didn't even realize I was running such an old version here... and being that my primary Lua experience is a few years back, I didn't know where to begin with tracking down this "issue" (which is a non-issue...)  Thank you for updating the documentation, and my apologies for using a 10 year old version.. apparently.  (I thought it was installed on my system, but it was in a bin & scripts directory that i've been moving around for years... 100% my bad.  Cheers on the project.

**Comment by dbolli** [comment]
I'm running lua 5.4.6 on macOS 14.1.1 and I needed to install [bit32 via luarocks](https://luarocks.org/modules/siffiejoe/bit32)

```
$ luarocks install bit32
```

then I added

```
bit32 = require( "bit32" )
```

to the first non-comment line of z80_regression_test.lua

then ran the lua script via

```
cd /path/to/LuaZ80-master
lua z80_regression_test.lua
```
and the lua script ran successfully.

```
Finished all tests successfully
Tested official instructions	422
Not tested official instructions	283
Tested undocumented instructions	93
Not tested undocumented instructions	470
Tested unrecognised instructions	0
not/tested: N/Y=offical n/y=official ./x=unknown
```

Regards,
Derek.

**Comment by robzed** [comment]
> I'm running lua 5.4.6 on macOS 14.1.1 and I needed to install [bit32 via luarocks](https://luarocks.org/modules/siffiejoe/bit32)
> 
Thanks for this report Derek. 

I'm developing on MacOS, but I haven't tried Lua 5.4 yet. 

Is there anything I can help with on this project?
